BootStrap: debootstrap
OSVersion: precise
MirrorURL: http://us.archive.ubuntu.com/ubuntu/

%runscript
    echo "hello, world. i am running..."

%post
    sed -i 's/$/ universe/' /etc/apt/sources.list
    apt-get -y update
    apt-get -y --force-yes install texlive-full
